# Generated by Django 5.1.4 on 2024-12-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
