# Generated by Django 5.1.4 on 2024-12-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_app', '0002_alter_item_url_alter_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='guid',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(),
        ),
    ]
