# Generated by Django 5.1.4 on 2024-12-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_app', '0003_item_guid_alter_item_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='last_fetched',
            field=models.DateTimeField(null=True),
        ),
    ]
