# Generated by Django 5.1.4 on 2024-12-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_app', '0004_source_last_fetched'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='title',
            field=models.TextField(default='', max_length=200),
        ),
    ]
