# Generated by Django 5.1.4 on 2025-01-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_app', '0005_source_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
