# Generated by Django 5.1.4 on 2025-01-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_app', '0006_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='description',
            field=models.TextField(default='', max_length=999),
        ),
    ]
