# Generated by Django 5.1.4 on 2025-01-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_app', '0007_source_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='last_etag',
            field=models.TextField(null=True),
        ),
    ]
