# Generated by Django 5.1.4 on 2025-01-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_app', '0008_source_last_etag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='last_etag',
            field=models.TextField(default=''),
        ),
    ]
